spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/nulltest
    username: sopt_naver_user
    password: 66666666
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#
#        dialect: org.hibernate.dialect.PostgreSQLDialect
