spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://now-sopt-database.cbayyeqey3do.ap-northeast-2.rds.amazonaws.com:5432/soptnaver
    username: sopt_naver
    password: 66666666
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
